-- BANQUET


CREATE DATABASE IF NOT EXISTS `BANQUET` CHARACTER SET 'utf8mb4';

USE `BANQUET`;























-- 用户表 USERS
CREATE TABLE IF NOT EXISTS `USERS` (
	`UID` INT NOT NULL AUTO_INCREMENT COMMENT '账户ID',
	`USERNAME` VARCHAR (255) NOT NULL COMMENT '账户名',
	`PASSWORD` VARCHAR (255) NOT NULL DEFAULT '$2a$12$5O4F/oSoMfsjpjlzHDHp9e89prBzQb3fhKLuQ8PEuhp.e7Rf/GbnG' COMMENT '密码哈希值, 初始明码:1212',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`UID`),
	UNIQUE KEY `UK_USERS_USERNAME` (`USERNAME`)
) ENGINE = INNODB AUTO_INCREMENT = 10000 DEFAULT CHARSET = utf8mb4 COMMENT = '用户表';


-- 用户详细信息表 USER_DETAILS
CREATE TABLE IF NOT EXISTS `USER_DETAILS` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`UID` INT NOT NULL COMMENT '账户ID',
	`EMAIL` VARCHAR (255) DEFAULT NULL COMMENT '邮箱',
	`PHONE` VARCHAR (255) DEFAULT NULL COMMENT '手机号',
	`BIRTH` DATE DEFAULT NULL COMMENT '出生日期',
	`GENDER` TINYINT (1) DEFAULT 0 COMMENT '性别, 0:男, 1:女',
	`IP` VARCHAR (255) DEFAULT NULL COMMENT '用户IP',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`),
	UNIQUE KEY `UK_USER_DETAILS_UID` (`UID`),
	UNIQUE KEY `UK_USER_DETAILS_EMAIL_PHONE` (`EMAIL`, `PHONE`),
	KEY `FK_USER_DETAILS_UID` (`UID`),
	CONSTRAINT `FK_USER_DETAILS_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户详细信息表';


-- 用户登录设备表 USER_DEVICES
CREATE TABLE IF NOT EXISTS `USER_DEVICES` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`UID` INT NOT NULL COMMENT '账户ID',
	`DEVICE_ID` VARCHAR (255) DEFAULT NULL COMMENT '登录设备ID',
-- 	`DEVICE_TYPE` ENUM('MOBILE', 'DESKTOP', 'TABLET') DEFAULT NULL COMMENT '登录设备类型',
	`DEVICE_TYPE` VARCHAR (255) DEFAULT NULL COMMENT '登录设备类型',
-- 	`DEVICE_LOGIN_METHOD` ENUM('PHONE_CODE', 'QR_CODE', 'EMAIL', 'ID_CARD', 'THIRD_PARTY') DEFAULT NULL COMMENT '登录设备方式, 0:账密登录, 1:手机验证码登录, 2:扫码登录, 3:邮箱登录, 4:身份证号登录, 5:三方登录',
	`DEVICE_LOGIN_METHOD` INT DEFAULT 0 COMMENT '登录设备方式, 0:账密登录, 1:手机验证码登录, 2:扫码登录, 3:邮箱登录, 4:身份证号登录, 5:三方登录',
	`DEVICE_LOGIN_IP` VARCHAR (255) DEFAULT NULL COMMENT '登录设备IP',
	`DEVICE_LASTLOGIN` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后一次登录时间',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`),
	KEY `FK_USER_DEVICES_UID` (`UID`),
	CONSTRAINT `FK_USER_DEVICES_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户登录设备表';


-- 用户实名认证表 USER_VERIFICATION
CREATE TABLE IF NOT EXISTS `USER_VERIFICATION` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`UID` INT NOT NULL COMMENT '账户ID',
	`REAL_NAME` VARCHAR (255) DEFAULT NULL COMMENT '实名真实姓名',
	`ID_CARD` VARCHAR (255) DEFAULT NULL COMMENT '实名身份证号',
	`VERIFIED` TINYINT(1) DEFAULT 0 COMMENT '认证是否已验证, 0:未验证, 1:已验证',
	`VERIFICATION_DATE` DATETIME(6) DEFAULT NULL COMMENT '认证验证日期',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`),
	UNIQUE KEY `UK_USER_VERIFICATION_UID` (`UID`),
	UNIQUE KEY `UK_USER_VERIFICATION_ID_CARD` (`ID_CARD`),
	KEY `FK_USER_VERIFICATION_UID` (`UID`),
	CONSTRAINT `FK_USER_VERIFICATION_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户实名认证表';


-- 用户三方账号表
CREATE TABLE IF NOT EXISTS `USER_SOCIAL` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`UUID` VARCHAR (255) NOT NULL COMMENT '第三方系统的唯一ID',
	`USERNAME` VARCHAR (255) DEFAULT NULL COMMENT '用户名',
	`NICKNAME` VARCHAR (255) DEFAULT NULL COMMENT '用户昵称',
	`AVATAR` VARCHAR (255) DEFAULT NULL COMMENT '用户头像',
	`BLOG` VARCHAR (255) DEFAULT NULL COMMENT '用户网址',
	`COMPANY` VARCHAR (255) DEFAULT NULL COMMENT '所在公司',
	`LOCATION` VARCHAR (255) DEFAULT NULL COMMENT '位置',
	`EMAIL` VARCHAR (255) DEFAULT NULL COMMENT '邮箱',
	`REMARK` VARCHAR (255) DEFAULT NULL COMMENT '用户备注',
-- 	`GENDER` ENUM('MALE', 'FEMALE', 'UNKNOWN') DEFAULT 'UNKNOWN' COMMENT '性别, 1:男, 2:女, 0:女, -1:未知',
	`GENDER` TINYINT (1) DEFAULT 0 COMMENT '性别, 1:男, 2:女, 0:女, -1:未知',
	`SOURCE` VARCHAR (255) DEFAULT NULL COMMENT '第三方用户来源',
	`TOKEN`  DEFAULT NULL COMMENT '用户授权的TOKEN信息',
	`RAW_USER_INFO`  DEFAULT NULL COMMENT '第三方平台返回的原始用户信息',
	`SNAPSHOT_USER`  DEFAULT NULL COMMENT '微信公众号 - 网页授权的登录时可用 微信针对网页授权登录，增加了一个快照页的逻辑，快照页获取到的微信用户的 uid oid 和头像昵称都是虚拟的信息',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户三方账号表';


-- 用户-三方账号关系表
CREATE TABLE IF NOT EXISTS `USER_SOCIAL_AUTH` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`UID` INT NOT NULL COMMENT '账户ID',
	`SAID` INT NOT NULL COMMENT '三方账号记录ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `UID`, `SAID`),
	KEY `FK_USER_SOCIAL_AUTH_UID` (`UID`),
	KEY `FK_USER_SOCIAL_AUTH_SAID` (`SAID`),
	CONSTRAINT `FK_USER_SOCIAL_AUTH_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`),
	CONSTRAINT `FK_USER_SOCIAL_AUTH_SOCIAL` FOREIGN KEY (`SAID`) REFERENCES `USER_SOCIAL` (`ID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户-三方账号关系表';















-- 用户身份表 USER_ROLES
CREATE TABLE IF NOT EXISTS `USER_ROLES` (
	`RID` INT NOT NULL AUTO_INCREMENT COMMENT '身份ID',
	`ROLE_NAME` VARCHAR (255) NOT NULL COMMENT '身份名',
	`ROLE_DESCRIPTION` TEXT DEFAULT NULL COMMENT '身份描述',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`RID`),
	UNIQUE KEY `UK_USER_ROLES_ROLE_NAME` (`ROLE_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户身份表';


-- 用户-身份关系表 USER_ROLES_RELATION
CREATE TABLE IF NOT EXISTS `USER_ROLES_RELATION` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`UID` INT NOT NULL COMMENT '账户ID',
	`RID` INT NOT NULL DEFAULT 1 COMMENT '身份ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `UID`, `RID`),
	KEY `FK_USER_ROLES_RELATION_UID` (`UID`),
	KEY `FK_USER_ROLES_RELATION_RID` (`RID`),
	CONSTRAINT `FK_USER_ROLES_RELATION_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`),
	CONSTRAINT `FK_USER_ROLES_RELATION_ROLES` FOREIGN KEY (`RID`) REFERENCES `USER_ROLES` (`RID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '用户-身份关系表';















-- 宴会类型表 BANQUET_TYPES
CREATE TABLE IF NOT EXISTS `BANQUET_TYPES` (
	`TID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会类型ID',
	`TYPE_NAME` VARCHAR (255) NOT NULL COMMENT '宴会类型名',
	`TYPE_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会类型描述',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`TID`),
	UNIQUE KEY `UK_BANQUET_TYPES_TYPE_NAME` (`TYPE_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会类型表';


-- 宴会场合表 BANQUET_OCCASIONS
CREATE TABLE IF NOT EXISTS `BANQUET_OCCASIONS` (
	`OID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会场合ID',
	`OCCASION_NAME` VARCHAR (255) NOT NULL COMMENT '宴会场合名',
	`OCCASION_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会场合描述',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`OID`),
	UNIQUE KEY `UK_BANQUET_OCCASIONS_OCCASION_NAME` (`OCCASION_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会场合表';


-- 宴会类型-场合关系表 BANQUET_TYPE_OCCASIONS
CREATE TABLE IF NOT EXISTS `BANQUET_TYPE_OCCASIONS` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`TID` INT NOT NULL COMMENT '宴会类型ID',
	`OID` INT NOT NULL COMMENT '宴会场合ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `TID`, `OID`),
	UNIQUE KEY `UK_BANQUET_TYPE_OCCASIONS_ID` (`ID`),
	KEY `FK_BANQUET_TYPE_OCCASIONS_TID` (`TID`),
	KEY `FK_BANQUET_TYPE_OCCASIONS_OID` (`OID`),
	CONSTRAINT `FK_BANQUET_TYPE_OCCASIONS_TYPES` FOREIGN KEY (`TID`) REFERENCES `BANQUET_TYPES` (`TID`),
	CONSTRAINT `FK_BANQUET_TYPE_OCCASIONS_OCCASIONS` FOREIGN KEY (`OID`) REFERENCES `BANQUET_OCCASIONS` (`OID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会类型-场合关系表';














-- 宴会表 BANQUETS
CREATE TABLE IF NOT EXISTS `BANQUETS` (
	`BID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会ID',
	`BANQUETS_NAME` VARCHAR (255) NOT NULL COMMENT '宴会名',
	`BANQUETS_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会描述',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`BID`),
	UNIQUE KEY `UK_BANQUETS_NAME` (`BANQUETS_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会表';


-- 宴会详细信息表 BANQUET_DETAILS
CREATE TABLE IF NOT EXISTS `BANQUET_DETAILS` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`BID` INT NOT NULL COMMENT '宴会ID',
	`BANQUET_START_TIME` DATETIME (6) NOT NULL COMMENT '宴会开始时间',
	`BANQUET_END_TIME` DATETIME (6) NOT NULL COMMENT '宴会结束时间',
	`BANQUET_VENUE` VARCHAR (255) NOT NULL COMMENT '宴会地点',
	`BANQUET_GUEST_COUNT` INT DEFAULT 1 COMMENT '宴会预计客人数量',
	`BANQUET_BUDGET` DECIMAL (18, 2) DEFAULT 0 COMMENT '宴会预算',
	`BANQUET_NOTES` TEXT DEFAULT NULL COMMENT '宴会备注',
	`BANQUET_IP` VARCHAR (255) DEFAULT NULL COMMENT '宴会IP',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`),
	KEY `FK_BANQUET_DETAILS_BID` (`BID`),
	CONSTRAINT `FK_BANQUET_DETAILS_BANQUETS` FOREIGN KEY (`BID`) REFERENCES `BANQUETS` (`BID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会详细信息表';


-- 宴会-用户关系表 BANQUET_CUSTOMERS
CREATE TABLE IF NOT EXISTS `BANQUET_CUSTOMERS` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`BID` INT NOT NULL COMMENT '宴会ID',
	`UID` INT NOT NULL COMMENT '用户ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `BID`, `UID`),
	KEY `FK_BANQUET_CUSTOMERS_BID` (`BID`),
	KEY `FK_BANQUET_CUSTOMERS_UID` (`UID`),
	CONSTRAINT `FK_BANQUET_CUSTOMERS_BANQUETS` FOREIGN KEY (`BID`) REFERENCES `BANQUETS` (`BID`),
	CONSTRAINT `FK_BANQUET_CUSTOMERS_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会-用户关系表';


-- 宴会-类型-场合关系表 BANQUET_TYPE_OCCASIONS_RELATION
CREATE TABLE IF NOT EXISTS `BANQUET_TYPE_OCCASIONS_RELATION` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`BID` INT NOT NULL COMMENT '宴会ID',
	`TOID` INT NOT NULL COMMENT '宴会类型-场合记录ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `BID`, `TOID`),
	KEY `FK_BANQUET_TYPE_OCCASIONS_RELATION_BID` (`BID`),
	KEY `FK_BANQUET_TYPE_OCCASIONS_RELATION_TOID` (`TOID`),
	CONSTRAINT `FK_BANQUET_TYPE_OCCASIONS_RELATION_BANQUETS` FOREIGN KEY (`BID`) REFERENCES `BANQUETS` (`BID`),
	CONSTRAINT `FK_BANQUET_TYPE_OCCASIONS_RELATION_TYPE_OCCASIONS` FOREIGN KEY (`TOID`) REFERENCES `BANQUET_TYPE_OCCASIONS` (`ID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会-类型-场合关系表';











-- 宴会楼层表 BANQUET_FLOORS
CREATE TABLE IF NOT EXISTS `BANQUET_FLOORS` (
	`FID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会楼层ID',
	`FLOOR_NUMBER` VARCHAR (255) NOT NULL COMMENT '宴会楼层号',
	`FLOOR_NAME` VARCHAR (255) NOT NULL COMMENT '宴会楼层名',
	`FLOOR_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会楼层描述',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`FID`),
	UNIQUE KEY `UK_BANQUET_FLOORS_FLOOR_NUMBER_NAME` (`FLOOR_NUMBER`, `FLOOR_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会楼层表';


-- 宴会包间表 BANQUET_ROOMS
CREATE TABLE IF NOT EXISTS `BANQUET_ROOMS` (
	`RID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会包间ID',
	`ROOM_NUMBER` VARCHAR (255) NOT NULL COMMENT '宴会包间号',
	`ROOM_NAME` VARCHAR (255) NOT NULL COMMENT '宴会包间名',
	`ROOM_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会包间描述',
	`ROOM_CAPACITY` INT DEFAULT 100 COMMENT '宴会包间最大容纳人数',
-- 	`ROOM_STATUS` ENUM('Available', 'Reserved', 'In Use', 'Maintenance', 'Cleaning', 'Setup', 'Closed') DEFAULT 'Available' COMMENT '宴会包间状态, 0:可用, 1:预定, 2:正在使用, 3:维修, 4:清洁, 5:布置, 6:封闭',
	`ROOM_STATUS` INT DEFAULT 0 COMMENT '宴会包间状态, 0:可用, 1:预定, 2:正在使用, 3:维修, 4:清洁, 5:布置, 6:封闭',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`RID`),
	UNIQUE KEY `UK_BANQUET_ROOMS_ROOM_NUMBER_NAME` (`ROOM_NUMBER`, `ROOM_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会包间表';


-- 宴会楼层-包间关系表 BANQUET_FLOOR_ROOMS
CREATE TABLE IF NOT EXISTS `BANQUET_FLOOR_ROOMS` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`FID` INT NOT NULL COMMENT '宴会楼层ID',
	`RID` INT NOT NULL COMMENT '宴会包间ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `FID`, `RID`),
	UNIQUE KEY `UK_BANQUET_FLOOR_ROOMS_ID` (`ID`),
	KEY `FK_BANQUET_FLOOR_ROOMS_FID` (`FID`),
	KEY `FK_BANQUET_FLOOR_ROOMS_RID` (`RID`),
	CONSTRAINT `FK_BANQUET_FLOOR_ROOMS_FLOORS` FOREIGN KEY (`FID`) REFERENCES `BANQUET_FLOORS` (`FID`),
	CONSTRAINT `FK_BANQUET_FLOOR_ROOMS_ROOMS` FOREIGN KEY (`RID`) REFERENCES `BANQUET_ROOMS` (`RID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会楼层-包间关系表';













-- 宴会-楼层-包间-坐席关系表 BANQUET_SEAT
CREATE TABLE IF NOT EXISTS `BANQUET_SEAT` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`BID` INT NOT NULL COMMENT '宴会ID',
	`FRID` INT NOT NULL COMMENT '宴会楼层-包间ID',
	`UID` INT NOT NULL COMMENT '用户ID',
	`TABLE_NUMBER` INT NOT NULL COMMENT '宴会桌号',
	`SEAT_NUMBER` INT NOT NULL COMMENT '宴会座位号',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
  
	PRIMARY KEY (`ID`, `BID`, `FRID`, `UID`),
	UNIQUE KEY `UK_BANQUET_SEAT` (`TABLE_NUMBER`, `SEAT_NUMBER`),
	KEY `FK_BANQUET_SEAT_BID` (`BID`),
	KEY `FK_BANQUET_SEAT_FRID` (`FRID`),
	KEY `FK_BANQUET_SEAT_UID` (`UID`),
	CONSTRAINT `FK_BANQUET_SEAT_BANQUETS` FOREIGN KEY (`BID`) REFERENCES `BANQUETS` (`BID`),
	CONSTRAINT `FK_BANQUET_SEAT_FLOOR_ROOMS` FOREIGN KEY (`FRID`) REFERENCES `BANQUET_FLOOR_ROOMS` (`ID`),
	CONSTRAINT `FK_BANQUET_SEAT_USERS` FOREIGN KEY (`UID`) REFERENCES `USERS` (`UID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会-楼层-包间-坐席关系表';










-- 宴会服务类别表 BANQUET_SERVICE_CATEGORY
CREATE TABLE IF NOT EXISTS `BANQUET_SERVICE_CATEGORY` (
	`SID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会服务类别ID',
	`CATEGORY_NAME` VARCHAR (255) NOT NULL COMMENT '宴会服务类别名',
	`CATEGORY_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会服务类别描述',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`SID`),
	UNIQUE KEY `UK_BANQUET_SERVICE_CATEGORY_CATEGORY_NAME` (`CATEGORY_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会服务类别表';


-- 宴会服务项表 BANQUET_SERVICE_ITEMS
CREATE TABLE IF NOT EXISTS `BANQUET_SERVICE_ITEMS` (
	`IID` INT NOT NULL AUTO_INCREMENT COMMENT '宴会服务项ID',
	`ITEM_NAME` VARCHAR (255) NOT NULL COMMENT '宴会服务项名',
	`ITEM_DESCRIPTION` TEXT DEFAULT NULL COMMENT '宴会服务项描述',
	`ITEM_PRICE` DECIMAL (18, 2) DEFAULT 0 COMMENT '宴会服务项价格',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`IID`),
	UNIQUE KEY `UK_BANQUET_SERVICE_ITEMS_SERVICE_NAME` (`ITEM_NAME`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会服务项表';


-- 宴会服务类别-服务项关系表 BANQUET_SERVICE_CATEGORY_ITEMS
CREATE TABLE IF NOT EXISTS `BANQUET_SERVICE_CATEGORY_ITEMS` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`SID` INT NOT NULL COMMENT '宴会服务类别ID',
	`IID` INT NOT NULL COMMENT '宴会服务项ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `SID`, `IID`),
	UNIQUE KEY `UK_BANQUET_SERVICE_CATEGORY_ITEMS_ID` (`ID`),
	KEY `FK_BANQUET_SERVICE_CATEGORY_ITEMS_SID` (`SID`),
	KEY `FK_BANQUET_SERVICE_CATEGORY_ITEMS_IID` (`IID`),
	CONSTRAINT `FK_BANQUET_SERVICE_CATEGORY_ITEMS_SERVICE_CATEGORY` FOREIGN KEY (`SID`) REFERENCES `BANQUET_SERVICE_CATEGORY` (`SID`),
	CONSTRAINT `FK_BANQUET_SERVICE_CATEGORY_ITEMS_ITEMS` FOREIGN KEY (`IID`) REFERENCES `BANQUET_SERVICE_ITEMS` (`IID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会服务类别-服务项关系表';











-- 宴会-服务类别-服务项关系表 BANQUET_SERVICES_RELATION
CREATE TABLE IF NOT EXISTS `BANQUET_SERVICE_CATEGORY_ITEMS_RELATION` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`BID` INT NOT NULL COMMENT '宴会ID',
	`SIID` INT NOT NULL COMMENT '宴会服务类别-服务项ID',
	
	`CREATETIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) COMMENT '建档时间',
	`LASTMODIFYTIME` DATETIME (6) DEFAULT CURRENT_TIMESTAMP (6) ON UPDATE CURRENT_TIMESTAMP (6) COMMENT '最后更新时间',
	
	PRIMARY KEY (`ID`, `BID`, `SIID`),
	KEY `FK_BANQUET_SERVICES_RELATION_BID` (`BID`),
	KEY `FK_BANQUET_SERVICES_RELATION_SIID` (`SIID`),
	CONSTRAINT `FK_BANQUET_SERVICES_RELATION_BANQUETS` FOREIGN KEY (`BID`) REFERENCES `BANQUETS` (`BID`),
	CONSTRAINT `FK_BANQUET_SERVICES_RELATION_SERVICE_ITEMS` FOREIGN KEY (`SIID`) REFERENCES `BANQUET_SERVICE_CATEGORY_ITEMS` (`ID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = '宴会-服务类别-服务项关系表';



























INSERT INTO `USER_ROLES` (`ROLE_NAME`) VALUES ('普通');
INSERT INTO `USER_ROLES` (`ROLE_NAME`) VALUES ('会员');
INSERT INTO `USER_ROLES` (`ROLE_NAME`) VALUES ('超级会员');
INSERT INTO `USER_ROLES` (`ROLE_NAME`) VALUES ('小黑屋');
INSERT INTO `USER_ROLES` (`ROLE_NAME`) VALUES ('管理');
INSERT INTO `USER_ROLES` (`ROLE_NAME`) VALUES ('超管');











-- 江底溺水的鱼 1212
INSERT INTO `USERS` (`USERNAME`, `PASSWORD`) VALUES ('江底溺水的鱼', '$2a$12$5O4F/oSoMfsjpjlzHDHp9e89prBzQb3fhKLuQ8PEuhp.e7Rf/GbnG');
-- admin admin
INSERT INTO `USERS` (`USERNAME`, `PASSWORD`) VALUES ('admin', '$2a$12$V1CVDB6A6prQ/Pot6iN9IePmhCfHb39RWJsbexuAjHVvmNNdqM/mO');
-- root root
INSERT INTO `USERS` (`USERNAME`, `PASSWORD`) VALUES ('root', '$2a$12$J5z7aJ0n9AzSNHecyF62yejju7IQ51KALvVIhA59hgK6EacTt00Fy');









INSERT INTO `USER_DETAILS` (`UID`) VALUES (10000);
INSERT INTO `USER_DETAILS` (`UID`) VALUES (10001);
INSERT INTO `USER_DETAILS` (`UID`) VALUES (10002);









INSERT INTO `USER_ROLES_RELATION` (`UID`, `RID`) VALUES (10000, 3);
INSERT INTO `USER_ROLES_RELATION` (`UID`, `RID`) VALUES (10001, 5);
INSERT INTO `USER_ROLES_RELATION` (`UID`, `RID`) VALUES (10002, 6);






INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10000, 'HUAWEI Pura 70 Ultra', 'MOBILE', '36.133.192.251');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10000, 'HUAWEI Mate 60 Pro+', 'MOBILE', '36.134.127.165');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10000, 'OnePlus 12', 'MOBILE', '1.231.0.255');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10002, 'IQOO 12', 'MOBILE', '59.83.247.108');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10000, 'IQOO 12 Pro', 'MOBILE', '246.18.243.192');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10002, 'HUAWEI', 'MOBILE', '217.227.254.7');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10001, 'OPPO', 'MOBILE', '102.3.122.251');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10002, 'OnePlus Ace 3 Pro', 'MOBILE', '123.250.6.14');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10001, 'IQOO 12', 'MOBILE', '253.100.235.69');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10002, 'IQOO Neo8 Pro', 'MOBILE', '131.0.154.104');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10001, 'IQOO 12 Pro', 'MOBILE', '59.9.209.8');
INSERT INTO `USER_DEVICES` (`UID`, `DEVICE_ID`, `DEVICE_TYPE`, `DEVICE_LOGIN_IP`) VALUES (10002, 'VIVO X100 Ultra', 'MOBILE', '87.225.166.253');





INSERT INTO `USER_VERIFICATION` (`UID`, `REAL_NAME`, `ID_CARD`) VALUES (10000, 'Xu You', '100');
INSERT INTO `USER_VERIFICATION` (`UID`, `REAL_NAME`, `ID_CARD`) VALUES (10001, 'Zhu Zhiyuan', '101');
INSERT INTO `USER_VERIFICATION` (`UID`, `REAL_NAME`, `ID_CARD`) VALUES (10002, '許慧敏', '102');













INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('主题宴');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('便宴');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('商务宴');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('国宴');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('家宴');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('招待会');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('正式宴');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('茶会');
INSERT INTO `BANQUET_TYPES` (`TYPE_NAME`) VALUES ('酒会');






INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('丧宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('乔迁宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('升学宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('升职宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('婚宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('寿宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('悼念宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('成年宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('新生宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('聚会宴');
INSERT INTO `BANQUET_OCCASIONS` (`OCCASION_NAME`) VALUES ('订婚宴');










INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('1F', '一楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('2F', '二楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('3F', '三楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('4F', '四楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('5F', '五楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('6F', '六楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('7F', '七楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('8F', '八楼');
INSERT INTO `BANQUET_FLOORS` (`FLOOR_NUMBER`, `FLOOR_NAME`) VALUES ('9F', '九楼');










INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1001', '1001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1002', '1002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1003', '1003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1004', '1004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1005', '1005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1006', '1006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1007', '1007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1008', '1008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('1009', '1009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2001', '2001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2002', '2002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2003', '2003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2004', '2004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2005', '2005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2006', '2006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2007', '2007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2008', '2008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('2009', '2009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3001', '3001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3002', '3002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3003', '3003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3004', '3004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3005', '3005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3006', '3006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3007', '3007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3008', '3008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('3009', '3009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4001', '4001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4002', '4002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4003', '4003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4004', '4004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4005', '4005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4006', '4006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4007', '4007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4008', '4008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('4009', '4009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5001', '5001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5002', '5002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5003', '5003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5004', '5004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5005', '5005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5006', '5006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5007', '5007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5008', '5008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('5009', '5009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6001', '6001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6002', '6002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6003', '6003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6004', '6004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6005', '6005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6006', '6006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6007', '6007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6008', '6008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('6009', '6009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7001', '7001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7002', '7002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7003', '7003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7004', '7004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7005', '7005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7006', '7006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7007', '7007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7008', '7008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('7009', '7009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8001', '8001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8002', '8002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8003', '8003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8004', '8004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8005', '8005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8006', '8006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8007', '8007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8008', '8008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('8009', '8009');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9001', '9001');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9002', '9002');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9003', '9003');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9004', '9004');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9005', '9005');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9006', '9006');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9007', '9007');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9008', '9008');
INSERT INTO `BANQUET_ROOMS` (`ROOM_NUMBER`, `ROOM_NAME`) VALUES ('9009', '9009');









INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 1);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 2);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 3);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 4);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 5);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 6);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 7);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 8);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (1, 9);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 10);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 11);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 12);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 13);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 14);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 15);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 16);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 17);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (2, 18);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 19);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 20);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 21);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 22);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 23);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 24);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 25);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 26);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (3, 27);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 28);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 29);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 30);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 31);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 32);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 33);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 34);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 35);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (4, 36);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 37);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 38);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 39);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 40);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 41);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 42);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 43);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 44);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (5, 45);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 46);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 47);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 48);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 49);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 50);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 51);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 52);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 53);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (6, 54);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 55);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 56);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 57);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 58);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 59);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 60);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 61);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 62);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (7, 63);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 64);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 65);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 66);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 67);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 68);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 69);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 70);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 71);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (8, 72);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 73);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 74);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 75);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 76);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 77);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 78);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 79);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 80);
INSERT INTO `BANQUET_FLOOR_ROOMS` (`FID`, `RID`) VALUES (9, 81);










INSERT INTO `BANQUET_SERVICE_CATEGORY` (`CATEGORY_NAME`) VALUES ('餐饮');
INSERT INTO `BANQUET_SERVICE_CATEGORY` (`CATEGORY_NAME`) VALUES ('装饰');
INSERT INTO `BANQUET_SERVICE_CATEGORY` (`CATEGORY_NAME`) VALUES ('礼品');
INSERT INTO `BANQUET_SERVICE_CATEGORY` (`CATEGORY_NAME`) VALUES ('音乐');
INSERT INTO `BANQUET_SERVICE_CATEGORY` (`CATEGORY_NAME`) VALUES ('活动');







INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('沙拉', 10.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('冷盘', 20.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('汤品', 10.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('烤肉', 30.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('红烧鱼', 40.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('烤鱼', 25.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('肉末茄子', 12.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('巴西烤肉', 12.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('口水鸡', 13.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('蛋糕', 50.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('水果拼盘', 20.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('冰淇淋', 10.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('苹果汁', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('西瓜汁', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('茶', 3.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('矿泉水', 1.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('冰红茶', 3.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('雪碧', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('百事可乐', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('葡萄汁', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('芒果汁', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('花束', 10.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('烛台', 10.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('定制餐具', 5.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('氛围灯光条', 10.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('气球', 2.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('布幔', 50.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('定制横幅', 100.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('定制签名墙', 150.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('拍照区', 200.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('迎宾区', 200.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('纪念品', 100.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('氛围背景音乐', 50.00);
INSERT INTO `BANQUET_SERVICE_ITEMS` (`ITEM_NAME`, `ITEM_PRICE`) VALUES ('表演', 200.00);








INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 1);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 2);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 3);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 4);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 5);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 6);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 7);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 8);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 9);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 10);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 11);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 12);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 13);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 14);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 15);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 16);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 17);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 18);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 19);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 20);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (1, 21);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 22);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 23);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 24);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 25);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 26);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 27);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 28);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 29);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 30);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (2, 31);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (3, 32);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (4, 33);
INSERT INTO `BANQUET_SERVICE_CATEGORY_ITEMS` (`SID`, `IID`) VALUES (5, 34);

















-- 删除表数据
-- 语法:TRUNCATE TABLE 数据表;
-- 语法:DELETE FROM 数据表;
-- DELETE FROM `USER_DETAILS`;
-- DELETE FROM `USER_DEVICES`;
-- DELETE FROM `USER_VERIFICATION`;
-- 
-- DELETE FROM `USER_SOCIAL_AUTH`;
-- DELETE FROM `USER_SOCIAL`;
-- 
-- DELETE FROM `USER_ROLES_RELATION`;
-- DELETE FROM `USER_ROLES`;
-- 
-- DELETE FROM `BANQUET_TYPE_OCCASIONS_RELATION`;
-- DELETE FROM `BANQUET_TYPE_OCCASIONS`;
-- DELETE FROM `BANQUET_OCCASIONS`;
-- DELETE FROM `BANQUET_TYPES`;
-- 
-- DELETE FROM `BANQUET_SEAT`;
-- DELETE FROM `BANQUET_CUSTOMERS`;
-- 
-- DELETE FROM `BANQUET_FLOOR_ROOMS`;
-- DELETE FROM `BANQUET_FLOORS`;
-- DELETE FROM `BANQUET_ROOMS`;
-- 
-- DELETE FROM `BANQUET_SERVICE_CATEGORY_ITEMS_RELATION`;
-- DELETE FROM `BANQUET_SERVICE_CATEGORY_ITEMS`;
-- DELETE FROM `BANQUET_SERVICE_CATEGORY`;
-- DELETE FROM `BANQUET_SERVICE_ITEMS`;
-- 
-- DELETE FROM `BANQUET_DETAILS`;
-- DELETE FROM `BANQUETS`;
-- 
-- DELETE FROM `USERS`;





-- 删除表
-- 语法:DROP TABLE 数据表;
DROP TABLE IF EXISTS `USER_DETAILS`;
DROP TABLE IF EXISTS `USER_DEVICES`;
DROP TABLE IF EXISTS `USER_VERIFICATION`;

DROP TABLE IF EXISTS `USER_SOCIAL_AUTH`;
DROP TABLE IF EXISTS `USER_SOCIAL`;

DROP TABLE IF EXISTS `USER_ROLES_RELATION`;
DROP TABLE IF EXISTS `USER_ROLES`;

DROP TABLE IF EXISTS `BANQUET_TYPE_OCCASIONS_RELATION`;
DROP TABLE IF EXISTS `BANQUET_TYPE_OCCASIONS`;
DROP TABLE IF EXISTS `BANQUET_OCCASIONS`;
DROP TABLE IF EXISTS `BANQUET_TYPES`;

DROP TABLE IF EXISTS `BANQUET_SEAT`;
DROP TABLE IF EXISTS `BANQUET_CUSTOMERS`;

DROP TABLE IF EXISTS `BANQUET_FLOOR_ROOMS`;
DROP TABLE IF EXISTS `BANQUET_FLOORS`;
DROP TABLE IF EXISTS `BANQUET_ROOMS`;

DROP TABLE IF EXISTS `BANQUET_SERVICE_CATEGORY_ITEMS_RELATION`;
DROP TABLE IF EXISTS `BANQUET_SERVICE_CATEGORY_ITEMS`;
DROP TABLE IF EXISTS `BANQUET_SERVICE_CATEGORY`;
DROP TABLE IF EXISTS `BANQUET_SERVICE_ITEMS`;

DROP TABLE IF EXISTS `BANQUET_DETAILS`;
DROP TABLE IF EXISTS `BANQUETS`;

DROP TABLE IF EXISTS `USERS`;






-- 查询数据库中存在的表数量
-- 语法:SELECT COUNT(*) AS `表数量` FROM `information_schema`.`tables` WHERE `table_schema` = '数据库名';
-- SELECT COUNT(*) AS `表数量` FROM `information_schema`.`tables` WHERE `table_schema` = 'BANQUET';





-- 返回数据表各种状态信息的结果集
-- SHOW TABLE STATUS LIKE 'USERS';



-- 查询最新AUTO_INCREMENT
-- SELECT AUTO_INCREMENT FROM information_schema.tables WHERE table_name = 'USERS' AND table_schema = DATABASE();



-- 查询最新记录ID
-- SELECT MAX(`ID`) FROM `USERS`;



-- 查询最新记录
-- SELECT * FROM `USERS` ORDER BY `ID` DESC LIMIT 1;


















